### ISSUE TITLE
hlp

### ISSUE THREAD

**Issue by 13285073101** [m-hasan-n/human-like-planning#3]
When I run hlp_experiment_protocols(1, 1, '80_20', 0),
The function or variable 'navi_examples' is not recognizable, I don’t know how to solve the problem. I am looking forward to your reply. Thank you.

**Comment by m-hasan-n** [comment]
Sorry for the late reply! Before running experiments, you have first to load the dataset and segment the human demonstrations. Run the following script:

load_segment_demonstrations
